# Generated by Django 4.1.1 on 2022-10-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edad", models.CharField(max_length=100, verbose_name="Edad")),
                (
                    "genero",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Genero"
                    ),
                ),
                (
                    "TipoVictima",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tipo victima",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado"),
                ),
            ],
            options={"verbose_name": "Personas", "verbose_name_plural": "Personas",},
        ),
        migrations.CreateModel(
            name="TipoVictima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Descripcion",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado"),
                ),
            ],
            options={
                "verbose_name": "Tipo victima",
                "verbose_name_plural": "Tipos victimas",
            },
        ),
    ]
