# Generated by Django 4.1.1 on 2022-10-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "divisionPostal",
                    models.DateField(max_length=100, verbose_name="Codigo postal"),
                ),
                (
                    "comuna",
                    models.DateTimeField(
                        blank=True, max_length=15, null=True, verbose_name="Comuna"
                    ),
                ),
                (
                    "lugar",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Lugar"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Direccion"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Editado"),
                ),
            ],
            options={"verbose_name": "Lugar", "verbose_name_plural": "Lugares",},
        ),
    ]
