# Generated by Django 4.2.2 on 2023-08-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitios', '0002_alter_lugar_comuna_alter_lugar_divisionpostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='divisionPostal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Codigo postal'),
        ),
    ]
