# Generated by Django 4.1.1 on 2022-11-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accidente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidente",
            name="descripcion",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Descripcion"
            ),
        ),
    ]
